apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 160-openshift-dev-tools
spec:
  modules:
    - name: gitops-repo
      variables:
        - name: provision
          value: false
        - name: server_name
          alias: mgmt_server_name
          value: management-server
    - name: gitops-namespace
      variables:
        - name: name
          alias: tools
          value: tools
    - name: gitops-artifactory
    - name: gitops-dashboard
    - name: gitops-pact-broker
    - name: gitops-tekton-resources
  variables:
    - name: resource_group_name
    - name: region
    - name: ibmcloud_api_key
      required: true
    - name: registry_namespace
      required: true
    - name: name_prefix
      alias: mgmt_name_prefix
      required: true
