apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 400-telco-cloud-oms
spec:
  modules:
    - name: ibm-resource-group
      variables:
        - name: provision
          value: false
        - name: resource_group_name
          alias: mgmt_resource_group_name
          scope: global
    - name: ibm-resource-group
      alias: cs_resource_group
      variables:
        - name: provision
          value: false
    - name: logdna
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
    - name: sysdig
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
    - name: namespace
      variables:
        - name: name
          value: tools
    - name: ibm-logdna-bind
    - name: sysdig-bind
    - name: ibm-image-registry
      variables:
        - name: registry_namespace
          required: true
          scope: global
    - name: argocd
    - name: dashboard
    - name: pactbroker
    - name: artifactory
    - name: sonarqube
    - name: tekton
    - name: tekton-resources
    - name: source-control
  variables:
    - name: resource_group_name
    - name: region
    - name: ibmcloud_api_key
      required: true
    - name: registry_namespace
      required: true
    - name: name_prefix
      alias: mgmt_name_prefix
      required: true
